version: "1.0.0"

services:
  postgres:
    container_name: postgres
    image: docker.io/postgres:latest
    env_file: .env
    ports:
      - 27017:5432
    volumes:
      - pgdata:/var/lib/postgresql/data 


volumes:
  pgdata: